version: '3'

services:

  backend:
    image: romulodocker/fact-checker-app-backend:1.0.1
    container_name: fca-api
    restart: on-failure
    ports:
      - 5000:5000

  frontend:
    image: romulodocker/fact-checker-app-frontend:1.0.0
    container_name: fca-ui
    ports:
      - 8080:5173
    depends_on:
      - backend